-- =========================================================================
-- Little Chef Pizza — schema.sql
-- Run this in the Supabase SQL editor on a fresh project.
-- Designed for Postgres 14+ / Supabase (uses auth.users, gen_random_uuid()).
-- =========================================================================

create extension if not exists pgcrypto;

-- -------------------------------------------------------------- profiles
-- One row per authenticated user (customer or admin). auth_user_id links
-- to Supabase's own auth.users table. See policies.sql + functions/ for
-- how username/password auth (no email) is layered on top of Supabase Auth.
create table public.profiles (
  id              uuid primary key default gen_random_uuid(),
  auth_user_id    uuid not null unique references auth.users(id) on delete cascade,
  username        text not null unique,
  full_name       text not null,
  phone           text not null,
  role            text not null default 'customer' check (role in ('customer','admin')),
  area            text,
  address         text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  constraint username_format check (username ~ '^[a-zA-Z0-9_.]{3,20}$')
);
create index idx_profiles_role on public.profiles(role);

-- ------------------------------------------------------------ categories
create table public.categories (
  id           uuid primary key default gen_random_uuid(),
  name         text not null unique,
  description  text,
  image_url    text,
  sort_order   int not null default 0,
  active       boolean not null default true
);

-- -------------------------------------------------------------- products
create table public.products (
  id           uuid primary key default gen_random_uuid(),
  category_id  uuid not null references public.categories(id) on delete restrict,
  name         text not null,
  description  text,
  image_url    text,
  -- Simple flat price OR size-based pricing (small/medium/large/family/half/full).
  price        numeric(10,2),
  sizes        jsonb,              -- e.g. {"S":690,"M":1180,"L":1790,"F":2650}
  available    boolean not null default true,
  featured     boolean not null default false,
  verified     boolean not null default true, -- false = needs manual menu verification
  sort_order   int not null default 0,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  constraint price_or_sizes check (price is not null or sizes is not null)
);
create index idx_products_category on public.products(category_id);
create index idx_products_available on public.products(available);

-- ----------------------------------------------------------------- deals
create table public.deals (
  id            uuid primary key default gen_random_uuid(),
  name          text not null,
  description   text,
  image_url     text,
  price         numeric(10,2) not null check (price >= 0),
  available     boolean not null default true,
  featured      boolean not null default false,
  verified      boolean not null default true,
  start_date    date,
  end_date      date,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create table public.deal_items (
  id          uuid primary key default gen_random_uuid(),
  deal_id     uuid not null references public.deals(id) on delete cascade,
  product_id  uuid not null references public.products(id) on delete restrict,
  size        text,               -- which size of the product this deal includes, if applicable
  quantity    int not null default 1 check (quantity > 0),
  note        text
);
create index idx_deal_items_deal on public.deal_items(deal_id);

-- --------------------------------------------------------- delivery_areas
-- Curated, admin-editable whitelist of Gujrat-city delivery localities.
-- The checkout UI must only allow selecting from this table — never free text.
create table public.delivery_areas (
  id         uuid primary key default gen_random_uuid(),
  name       text not null unique,
  active     boolean not null default true,
  sort_order int not null default 0
);

-- ------------------------------------------------------------ site_settings
-- Generic key/value store so operational values (delivery charge, hours,
-- etc.) can change without a redeploy.
create table public.site_settings (
  key         text primary key,
  value       jsonb not null,
  updated_at  timestamptz not null default now()
);

-- -------------------------------------------------------------------- orders
create table public.orders (
  id                        uuid primary key default gen_random_uuid(),
  order_number              text not null unique,       -- e.g. LCP-10042, generated by sequence below
  user_id                   uuid references public.profiles(id) on delete set null,
  customer_type             text not null check (customer_type in ('customer','guest')),
  customer_name             text not null,
  customer_phone            text not null,
  order_type                text not null check (order_type in ('delivery','takeaway','dine-in')),
  delivery_area             text,
  delivery_address          text,
  subtotal                  numeric(10,2) not null check (subtotal >= 0),
  delivery_charge           numeric(10,2),               -- null = TBD, configurable via site_settings later
  discount                  numeric(10,2) not null default 0,
  total                     numeric(10,2) not null check (total >= 0),
  status                    text not null default 'pending' check (status in ('pending','delivered')),
  payment_method            text default 'cash' check (payment_method in ('cash','online')),
  payment_status            text default 'unpaid' check (payment_status in ('unpaid','paid')),
  cancellation_acknowledged boolean not null default false,
  created_at                timestamptz not null default now(),
  delivered_at              timestamptz,
  constraint delivery_requires_area_address check (
    order_type <> 'delivery' or (delivery_area is not null and delivery_address is not null)
  )
);
create index idx_orders_user on public.orders(user_id);
create index idx_orders_status on public.orders(status);
create index idx_orders_created on public.orders(created_at desc);

-- Sequence + helper for human-readable order numbers (never trust JS timestamps).
create sequence public.order_number_seq start 10001;
create or replace function public.next_order_number() returns text
language sql as $$ select 'LCP-' || nextval('public.order_number_seq')::text $$;

-- --------------------------------------------------------------- order_items
-- Immutable snapshot of each product line at the moment of purchase.
create table public.order_items (
  id                      uuid primary key default gen_random_uuid(),
  order_id                uuid not null references public.orders(id) on delete cascade,
  product_id              uuid references public.products(id) on delete set null,
  product_name_snapshot   text not null,
  unit_price_snapshot     numeric(10,2) not null check (unit_price_snapshot >= 0),
  quantity                int not null check (quantity > 0),
  line_total              numeric(10,2) not null check (line_total >= 0)
);
create index idx_order_items_order on public.order_items(order_id);

-- --------------------------------------------------------------- order_deals
create table public.order_deals (
  id                    uuid primary key default gen_random_uuid(),
  order_id              uuid not null references public.orders(id) on delete cascade,
  deal_id               uuid references public.deals(id) on delete set null,
  deal_name_snapshot    text not null,
  deal_price_snapshot   numeric(10,2) not null check (deal_price_snapshot >= 0),
  quantity              int not null check (quantity > 0),
  line_total            numeric(10,2) not null check (line_total >= 0)
);
create index idx_order_deals_order on public.order_deals(order_id);

-- ------------------------------------------------------------- updated_at
create or replace function public.set_updated_at() returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end; $$;

create trigger trg_profiles_updated before update on public.profiles for each row execute function public.set_updated_at();
create trigger trg_products_updated before update on public.products for each row execute function public.set_updated_at();
create trigger trg_deals_updated before update on public.deals for each row execute function public.set_updated_at();
